apiVersion: v1
kind: Service
metadata:
  name: aceest-svc
  namespace: aceest
spec:
  selector:
    app: aceest-fitness
    color: blue
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
